version: '2'
services:
  listener:
      build:
        context: .
        dockerfile: dockerfile.listener
      ports: ['3000:3000', '1337:1337']
  nlp:
      build:
        context: .
        dockerfile: dockerfile.nlp
      ports: ['5000:5000']